# Generated by Django 5.0.7 on 2024-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_contact_author_alter_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
